version: 2

jobs:
  build:
    docker:
      - image: ubuntu:16.04
    branches:
      only:
        - /tkgil\/.*/
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name:
          command: |
             echo "deb [trusted=yes] http://download.tizen.org/tools/latest-release/Ubuntu_16.04/ /" >> /etc/apt/sources.list
             apt upgrade
      - run:
          name: install packages
	  command: |
	     apt upgrade
             apt install -y build-essential git scons libtool autoconf valgrind doxygen wget unzip chrpath gbs
      - run:
          name: Run build for iotivity
          command: EXEC_MODE=true ./gbsbuild.sh