version: 2

jobs:
  build:
    docker:
      - image: ubuntu:16.04
    branches:
      only:
        - /tkgil\/.*/
    working_directory: ~/repo	
    steps:
      - checkout
      - run:
          name: Run build for iotivity
          command: date